// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wcindicator.api.Models;

namespace wcindicator.api.Migrations
{
    [DbContext(typeof(WCIndicatorContext))]
    partial class WCIndicatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wcindicator.api.Models.StatusReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ReportTime");

                    b.Property<int>("Status");

                    b.Property<TimeSpan>("StatusDuration");

                    b.HasKey("Id");

                    b.ToTable("StatusUpdates");

                    b.HasData(
                        new { Id = 1L, ReportTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Status = 0, StatusDuration = new TimeSpan(0, 0, 0, 0, 0) }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
